### ISSUE TITLE
CI fails: $ref target metadata.json of aiidalab-qe is no longer resolveable

### ISSUE THREAD

**Issue by SimonStier** [BIG-MAP/big-map-registry#125]
$refs point to https://aiidalab.github.io/aiidalab-qe/metadata.json, see
https://github.com/BIG-MAP/big-map-registry/blob/eb1058ffeb2385f97b6a0b3d484f4e5ca8b07ece/apps.yaml#L40-L50

... which was removed some time ago and is no longer hosted by github-pages, see:
* https://github.com/aiidalab/aiidalab-qe/pull/52
* https://github.com/aiidalab/aiidalab-qe/pull/124/files

**Comment by tsthakur** [comment]
Thank you for pointing this out. It has been fixed now and shouldn't block any PRs.
